version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: env.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py

# python:
#   # Install our python package before building the docs
#   install:
#     - requirements: docs/requirements.txt
#     - method: pip
#       path: .

formats:
  - pdf
  - epub
