name: Deploy static content to Pages

on:
  pull_request:
    types:
      - closed
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-n-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if PR is from release branch to main
        id: check-pr
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} == "main" && ${{ github.event.pull_request.head.ref }} =~ ^release-v.*$ ]]; then
            echo "PR is from a release branch to main."
            echo "::set-output name=trigger_deploy::true"
          else
            echo "PR is not from a release branch to main."
            echo "::set-output name=trigger_deploy::false"
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install package and docs optional dependencies
        run: pip install .[doc]
      - name: build docs
        run: cd docs && make html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/build/html'
      - name: Deploy to GitHub Pages
        if: steps.check-pr.outputs.trigger_deploy == 'true'
        id: deployment
        uses: actions/deploy-pages@v2
